# Generated by Django 2.2.12 on 2020-08-03 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_exercice', models.CharField(max_length=100)),
                ('nom_exercice', models.CharField(max_length=200)),
                ('difficulte_exercice', models.IntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise_weight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadlift_weight_serie', models.FloatField(default=20)),
                ('squat_weight_serie', models.FloatField(default=20)),
                ('overhead_press_weight_serie', models.FloatField(default=10)),
                ('bench_press_weight_serie', models.FloatField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('max_squat', models.FloatField(default=20)),
                ('max_deadlift', models.FloatField(default=20)),
                ('max_overhead_press', models.FloatField(default=20)),
                ('max_bench_press', models.FloatField(default=20)),
            ],
        ),
        migrations.CreateModel(
            name='Weekly_routine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField(default=1)),
                ('temps_recup', models.IntegerField(default=3)),
                ('nombre_series', models.IntegerField(default=3)),
                ('nombre_reps_serie1', models.IntegerField(default=10)),
                ('nombre_reps_serie2', models.IntegerField(default=10)),
                ('nombre_reps_serie3', models.IntegerField(default=10)),
                ('nombre_reps_serie4', models.IntegerField(default=10)),
                ('nombre_reps_serie5', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_programme', models.CharField(max_length=200)),
                ('nom_variante_programme', models.CharField(max_length=200)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appli.Utilisateur')),
            ],
        ),
    ]
