# Generated by Django 3.1 on 2020-08-25 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appli', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('week_number', models.IntegerField()),
                ('exercise', models.CharField(max_length=200)),
                ('reps_number', models.IntegerField()),
                ('max_weight', models.FloatField()),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appli.utilisateur')),
            ],
        ),
    ]
