# Generated by Django 3.1 on 2020-08-28 11:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appli', '0003_auto_20200827_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_record',
            name='date',
            field=models.DateField(default=datetime.date(2020, 8, 28)),
        ),
    ]
