# Generated by Django 3.1 on 2020-08-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appli', '0004_auto_20200828_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_record',
            name='reps_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='daily_record',
            name='week_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='daily_record',
            name='weight',
            field=models.FloatField(default=20),
        ),
    ]
