# Generated by Django 3.1 on 2020-09-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appli', '0006_auto_20200828_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_record',
            name='max_of_the_day',
            field=models.FloatField(default=20),
        ),
    ]
