# Generated by Django 3.1 on 2020-09-22 15:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appli', '0008_auto_20200922_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_record',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 9, 22, 15, 55, 9, 452169)),
        ),
    ]
