# Generated by Django 3.1 on 2020-09-22 20:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appli', '0010_auto_20200922_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_record',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 9, 22, 20, 38, 19, 520015)),
        ),
    ]
