# Generated by Django 3.1.1 on 2020-10-05 22:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appli', '0016_auto_20200930_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_record',
            name='fifth_exercise_assistance_work_name',
            field=models.CharField(default='test_exercise', max_length=200),
        ),
        migrations.AddField(
            model_name='daily_record',
            name='fifth_exercise_assistant_work_weight',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='daily_record',
            name='first_exercise_assistance_work_name',
            field=models.CharField(default='test_exercise', max_length=200),
        ),
        migrations.AddField(
            model_name='daily_record',
            name='first_exercise_assistant_work_weight',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='daily_record',
            name='fourth_exercise_assistance_work_name',
            field=models.CharField(default='test_exercise', max_length=200),
        ),
        migrations.AddField(
            model_name='daily_record',
            name='fourth_exercise_assistant_work_weight',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='daily_record',
            name='second_exercise_assistance_work_name',
            field=models.CharField(default='test_exercise', max_length=200),
        ),
        migrations.AddField(
            model_name='daily_record',
            name='second_exercise_assistant_work_weight',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='daily_record',
            name='third_exercise_assistance_work_name',
            field=models.CharField(default='test_exercise', max_length=200),
        ),
        migrations.AddField(
            model_name='daily_record',
            name='third_exercise_assistant_work_weight',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='daily_record',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 10, 5, 22, 30, 24, 291281)),
        ),
    ]
