# Generated by Django 3.1.1 on 2020-10-06 11:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('appli', '0017_auto_20201005_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_record',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 10, 6, 11, 30, 1, 130782, tzinfo=utc)),
        ),
    ]
